spring:
  application:
    name: agent

github:
  owner: philippelin
  repo: lab_mcp_ai_agent_springboot

openai:
  api-key: ${API_KEY:demo}
  model: gpt-4o-mini
  timeout-seconds: 60

mcp:
  base-url: ${MCP_BASE_URL:http://localhost:3333}
  path: ${MCP_PATH:/mcp}

management:
  endpoints:
    web:
      exposure:
        include: health,info